### ISSUE TITLE
Brush not working

### ISSUE THREAD

**Issue by PixelNotFound** [IntellectualSites/FastAsyncWorldEdit-1.13#151]
# Bug report for FastAsyncWorldEdit 1.13.2

**[REQUIRED] FastAsyncWorldEdit Version Number:** 

fawe version=> [10:33:30 INFO]: FastAsyncWorldEdit-1.13-110 by Empire92
[10:33:30 INFO]: ------------------------------------
[10:33:30 INFO]: - DATE: May 12, 2019 12:00:00 AM
[10:33:30 INFO]: - COMMIT: e72a5cf
[10:33:30 INFO]: - BUILD: 110
[10:33:30 INFO]: - PLATFORM: bukkit
[10:33:30 INFO]: ------------------------------------
[10:33:30 INFO]: Platforms:
[10:33:30 INFO]: - Bukkit
[10:33:30 INFO]: Capabilities:
[10:33:30 INFO]: - GAME_HOOKS: Bukkit
[10:33:30 INFO]: - CONFIGURATION: Bukkit
[10:33:30 INFO]: - USER_COMMANDS: Bukkit
[10:33:30 INFO]: - PERMISSIONS: Bukkit
[10:33:30 INFO]: - WORLDEDIT_CUI: Bukkit
[10:33:30 INFO]: - WORLD_EDITING: Bukkit
[10:33:30 INFO]: ------------------------------------
[10:33:30 INFO]: Wiki: https://github.com/boy0001/FastAsyncWorldedit/wiki

Issue is on both breaking and normal/
**[REQUIRED] Spigot/Paper Version Number:** 

[10:33:53 INFO]: Previous version: git-Paper-625 (MC: 1.13.2)
[10:33:53 INFO]: Checking version, please wait...
[10:33:53 INFO]: You are running the latest version
**Links to config.yml and config-legacy.yml file:** 

**[REQUIRED] Description of the problem:**

When someone uses brush it outputs alot of error. https://hastebin.com/hajuhoyibi.bash
**Plugins being used on the server:**

**How to replicate**:

/br sphere #copy
**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.13.2](https://ci.athion.net/job/FastAsyncWorldEdit-Breaking/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by IronApollo** [comment]
Hey, will you try shutting the server down, disabling persistent brushes in the config.yml, starting the server, using the brush again and seeing if the error continues? Thanks.

**Comment by PixelNotFound** [comment]
This has fixed it, why is this broken option enabled as default? And why does this happen and what do i miss by turning this option off? @IronApollo

**Comment by IronApollo** [comment]
Persistent brushes was a feature added that applies NBT data to the tool in question which holds information about the brush you applied to it, so next time it's used, it can bind the brush to that tool without having to retype the command.

This is a feature defaultly enabled because it's a feature that, when working, helps save time and frustration by allowing you to just pick up where you left off with that brush tool.

By turning it off, you now lose the feature described, but it's nothing to worry about. It's simply a quality of life feature.

I looked at that portion of the code the other day, and it looks like there may be a misplaced null check.

Glad you got it working, though! Closed.

**Comment by PixelNotFound** [comment]
Thanks for your help!

**Comment by PixelNotFound** [comment]
@IronApollo How can i know when a fixed is made so i can reenable this option, i am on fawe breaking 1.13.2

**Comment by IronApollo** [comment]
I think it might have already been fixed. Are you using the latest release?
