### ISSUE TITLE
Command snow is not working correctly, please fix it!

### ISSUE THREAD

**Issue by Truger23** [IntellectualSites/FastAsyncWorldEdit-1.13#318]
# Bug report for FastAsyncWorldEdit 1.15.1

Hello, command //snow is not working correctly. When I use that command, snow is only created on grass and not grass blocks at all.

**Comment by MattBDev** [comment]
Whenever I see someone say "please fix it!!!"  in their issue title I feel like just shouting back "PLEASE PAY ME"  because we work on the plugin for free in the little free time we have. We open sourced it for a reason.

Anyways, you didn't fill out the template but instead decided to delete it. I hope you enjoyed my rant. I'm closing your issue now
