### ISSUE TITLE
Craftscripts not working anymore.

### ISSUE THREAD

**Issue by bidule995** [IntellectualSites/FastAsyncWorldEdit-1.13#46]
# Bug report for FastAsyncWorldEdit 1.13.x

**Debug paste link**:
https://hastebin.com/wumewebosu

**Description of the problem:**
Craftscripts are not working anymore in 1.13. It displays an error message saying it is impossible to find the item in the hand (even if I got one).
![image](https://user-images.githubusercontent.com/16438002/52912168-01f45980-32ae-11e9-9735-342dc3d76aae.png)

**How to replicate**:
Simply by trying to use any Craftscript.

**Checklist**:
- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FAWE for 1.13.x](https://ci.athion.net/job/FAWE-1.13/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by TheoRetisch1** [comment]
Any news about this problem? >3 I miss the build tools so much :/

**Comment by MattBDev** [comment]
It's being addressed in the commanding branch.

**Comment by Combustible** [comment]
Spent a bunch of time working on this today - it looks like this problem is not CraftScripts itself - but that the Build Commands script (build.js) needs to be significantly updated to the new WorldEdit API. This is not a trivial task - but I also don't think it's a bug against FAWE itself. I started updating some of the build.js script but yikes, it's a lot of work. Hopefully someone eventually updates the entire thing because it's so useful. 

Maybe the bug should be against this repo? https://github.com/boy0001/CraftScripts/
