### ISSUE TITLE
Fill function seems to use a diamond shape instead of a circular pattern.

### ISSUE THREAD

**Issue by mibby** [IntellectualSites/FastAsyncWorldEdit-1.13#53]
Paper dev 525 (Spigot 1.13.2)
FAWE 1.13 compiled as of commit https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/commit/24fbc86cdd79b8ce13359342bc422ce1fb25a0d2

Got a report from a heavy worldedit user that the fill function behavior seems to be broken, or at the very least different from vanilla.

> the //fill function seems to do a diamond shaped filling instead of a circle shape as it used to do. Not sure if it's normal or on purpose but it's not a "bug" in itself, just a difference.

**Comment by Pangamma** [comment]
TBH, a diamond pattern is more efficient.

**Comment by SirYwell** [comment]
I think @mibby wants to outline that //fill has an unexpected result. On the image, you can see the result of `//fill dirt 10` the concrete blocks are marking the radius (10 + 1, I don't know how it handles the radius normally).
![image](https://user-images.githubusercontent.com/11150076/54671557-6cd7c100-4af6-11e9-8012-35980476f2a5.png)

**Comment by AeSix** [comment]
This explains a few things for myself.  I think this is similar behavior to //fixwater as well, which I just thought I was going batty, since it's difficult to see the shape produced for //fixwater.

Old behavior was to do a cylindrical fill, resulting in something more akin to //cyl dirt 10 1
https://puu.sh/D32F1/2735d3454d.png  (//cyl dirt 10 1  - with FAWE)
https://puu.sh/D32IS/266f318e82.png  (//fill dirt 10  - with WorldEdit 7 beta 5)

**Comment by mibby** [comment]
@SirYwell is correct. The behavior changed from a cylindrical-type fill with vanilla worldedit to a diamond-like pattern instead.

Still broken as of commit https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/commit/85bfd16d7c16613e79f49d3acaa17007c09baa3e (3/25 compile).

Tested with ``/fill dirt 10``.
![link3](https://i.imgur.com/M2ujAIE.png)
