### ISSUE TITLE
CFI Command Unknown

### ISSUE THREAD

**Issue by Vexmate** [IntellectualSites/FastAsyncWorldEdit-1.13#78]
# Bug report for FastAsyncWorldEdit 1.13.x

**Debug paste link**:
https://hastebin.com/alugobulas

**Description of the problem:**
//cfi command unknown but things like //sphere and //cyl work

**How to replicate**:
Just type //cfi

**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FAWE for 1.13.x](https://ci.athion.net/job/FAWE-1.13/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by SirYwell** [comment]
You're possibly using an outdated dev version, but the command is unknown in the current version too.

**Comment by Vexmate** [comment]
We downloaded the latest version from https://empcraft.com/fawe/download/ and even doing //cfi (url) doesn't work. Is there something we are missing?

**Comment by IronApollo** [comment]
CFI requires PlotSquared (not sure why off the top of my head but that's how it is). Unless you have PlotSquared installed, the command does not register.

**Comment by AeSix** [comment]
Perhaps CFI can be addressed once FAWE is in a stable state and fully compatible with P2 (which seems selfish, but I *think* once FAWE is compatible with P2, it should be compatible with everything else as well?)  It seems like it'll take a lot of work to remove the P2 dependency from CFI... or it could just be a silly non-required hard dependency and be fixed with a simple build.  Either way though, I can't imagine fixing CFI before other base issues would be well for the project.

**Comment by boy0001** [comment]
Fixed
