### ISSUE TITLE
FAWE Failed to Intialize

### ISSUE THREAD

**Issue by cakebomb999** [IntellectualSites/FastAsyncWorldEdit-1.13#83]
After i installed FAWE, everytime the exact error shows up, without FAWE worldedit is doing fine, so WE cannot be the Problem. 

LOG: 

[latest.txt](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/files/3010840/latest.txt)

- [] I included a `/fawe debugpaste` link (Not Possible, because the Plugin didn´t load)
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FAWE for 1.13.x](https://ci.athion.net/job/FAWE-1.13/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by Draycia** [comment]
FAWE-1.13 is a fork of WE and does not hook into it. Either use WE7 or FAWE, not both. 

Since you're using PlotSquared, your only options are to ditch either FAWE or P2 for the time being.

FAWE has not been updated to match WE7 and you can check the progress on that in the [new-vector-system](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/tree/new-vector-system) branch.

**Comment by MattBDev** [comment]
Closing because Draycia explained what happened here.
